name: continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: '**' 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: ./Azure

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./Azure

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Azure