name: deploy-prd

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["continuous-integration"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: ./Azure
      ARM_CLIENT_ID: "91f77ba6-fa15-48a8-b947-248659d73176"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      ARM_SUBSCRIPTION_ID: "2d518713-c5a2-4fcb-a600-307c349add12"
      ARM_TENANT_ID: "335776b5-3fba-4122-bcef-84458b1b8201"
      ARM_MSI_ENDPOINT: false
      ARM_USE_MSI: false

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -input=false -backend-config="resource_group_name=idguard-tf" -backend-config="storage_account_name=idguardtfstate" -backend-config="container_name=prd" -backend-config="key=dev.terraform.tfstate"
      working-directory: ./Azure

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Azure

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve -no-color -var="service_name=idguard" -var-file="config/idguard.tfvars" -var-file="config/prd.tfvars" 
      working-directory: ./Azure